In [1]:
import pandas as pd
import numpy as np

In [5]:
df_TR = pd.read_excel('../datos.xlsx', sheet_name='TR', header=None)
df_TR

0         1         2         3         4         5  6
0    1  0.667624  0.690085  0.030010  0.046070  0.730112  1
1    2  0.117142  0.561566  0.292938  0.902749  0.221894  0
2    3  0.891872  0.200137  0.255566  0.196651  0.244722  1
3    4  0.396319  0.929217  0.093175  0.916880  0.038861  0
4    5  0.945067  0.719301  0.254839  0.685144  0.384446  1
5    6  0.283729  0.649631  0.822075  0.221705  0.164641  0
6    7  0.394948  0.967419  0.317851  0.378759  0.862295  0
7    8  0.354521  0.878401  0.379587  0.538370  0.691997  0
8    9  0.350419  0.978717  0.802632  0.287180  0.152363  1
9   10  0.593596  0.204441  0.868701  0.705679  0.266975  1
10  11  0.708215  0.586039  0.693940  0.760597  0.619426  0
11  12  0.113410  0.287906  0.405895  0.850640  0.115194  1
12  13  0.963426  0.889605  0.098037  0.710435  0.190766  0
13  14  0.037876  0.697449  0.839394  0.118903  0.635160  0
14  15  0.795748  0.735194  0.267864  0.547854  0.779573  0
15  16  0.676406  0.501012  0.525795  0.684099  0.541232  1
16  17  0.024903  0.847810  0.725192  0.949080  0.701082  1
17  18  0.855563  0.870876  0.537478  0.668618  0.154085  1
18  19  0.921575  0.413062  0.353160  0.537657  0.185702  0
19  20  0.683849  0.334699  0.436643  0.392756  0.223471  1
20  21  0.768292  0.110461  0.845509  0.561618  0.527543  0
21  22  0.851133  0.526669  0.983305  0.041332  0.134673  0
22  23  0.332123  0.953593  0.705941  0.604675  0.826630  0
23  24  0.922595  0.396121  0.993722  0.251626  0.399368  1
24  25  0.560770  0.837124  0.929643  0.738090  0.188357  1
25  26  0.745331  0.428350  0.561796  0.598045  0.020410  1
26  27  0.739440  0.497040  0.342638  0.137493  0.814919  1
27  28  0.165416  0.258485  0.188872  0.696309  0.796666  1
28  29  0.681985  0.905493  0.437910  0.692599  0.419536  0
29  30  0.601472  0.912202  0.901026  0.108798  0.265434  0

In [6]:
df_TF = pd.read_excel('../datos.xlsx', sheet_name='TF', header=None)
df_TF

0         1         2         3         4         5  6
0    1  0.397622  0.428217  0.858496  0.007184  0.600111  1
1    2  0.329814  0.130692  0.606923  0.714222  0.598794  0
2    3  0.131990  0.728759  0.407384  0.241585  0.385890  1
3    4  0.754397  0.790543  0.133378  0.545250  0.259176  0
4    5  0.572327  0.963825  0.389474  0.254701  0.653624  1
5    6  0.978172  0.611061  0.623636  0.728672  0.064648  0
6    7  0.052682  0.461421  0.041184  0.626790  0.950707  0
7    8  0.746411  0.945319  0.750373  0.794147  0.054971  0
8    9  0.045503  0.772036  0.013733  0.193428  0.336871  1
9   10  0.846090  0.539100  0.465497  0.658346  0.872612  1
10  11  0.700513  0.961111  0.152718  0.206569  0.897410  0
11  12  0.971126  0.750723  0.453522  0.603551  0.838900  1
12  13  0.983242  0.312239  0.675879  0.995754  0.429438  0
13  14  0.761437  0.927513  0.753134  0.489123  0.825192  0
14  15  0.221859  0.754507  0.369178  0.994234  0.314729  0
15  16  0.072076  0.011827  0.740439  0.151784  0.389506  1
16  17  0.814993  0.237636  0.014405  0.440771  0.713054  1
17  18  0.327496  0.812191  0.136471  0.564322  0.269415  1
18  19  0.156341  0.157215  0.621872  0.473137  0.898678  0
19  20  0.738788  0.414936  0.830524  0.046897  0.314245  1
20  21  0.389158  0.029158  0.590971  0.931412  0.685464  0
21  22  0.586306  0.257024  0.302260  0.314716  0.276377  0
22  23  0.217847  0.845294  0.027532  0.388072  0.834331  0
23  24  0.285260  0.366960  0.276669  0.522499  0.512757  1
24  25  0.188385  0.712898  0.699959  0.582345  0.822652  1
25  26  0.336629  0.342178  0.857116  0.077685  0.835385  1
26  27  0.691430  0.092307  0.404190  0.989561  0.293272  1
27  28  0.343659  0.115863  0.818831  0.140722  0.292940  1
28  29  0.234806  0.585645  0.972211  0.248070  0.999263  0
29  30  0.773302  0.854541  0.576700  0.787127  0.083921  0

In [9]:
a_TR = df_TR.to_numpy()
a_TF = df_TF.to_numpy()
a_TR, a_TF

(array([[1.00000000e+00, 6.67624248e-01, 6.90085081e-01, 3.00098339e-02,
         4.60695128e-02, 7.30111778e-01, 1.00000000e+00],
        [2.00000000e+00, 1.17142176e-01, 5.61565548e-01, 2.92937516e-01,
         9.02748627e-01, 2.21894401e-01, 0.00000000e+00],
        [3.00000000e+00, 8.91872162e-01, 2.00136976e-01, 2.55566313e-01,
         1.96651158e-01, 2.44722066e-01, 1.00000000e+00],
        [4.00000000e+00, 3.96319265e-01, 9.29217089e-01, 9.31750047e-02,
         9.16879885e-01, 3.88614082e-02, 0.00000000e+00],
        [5.00000000e+00, 9.45066555e-01, 7.19301068e-01, 2.54839085e-01,
         6.85144373e-01, 3.84445840e-01, 1.00000000e+00],
        [6.00000000e+00, 2.83728727e-01, 6.49631466e-01, 8.22074857e-01,
         2.21704946e-01, 1.64641489e-01, 0.00000000e+00],
        [7.00000000e+00, 3.94947705e-01, 9.67419458e-01, 3.17850647e-01,
         3.78758743e-01, 8.62294540e-01, 0.00000000e+00],
        [8.00000000e+00, 3.54520929e-01, 8.78400593e-01, 3.79587438e-01,
         5

In [11]:
x_TR = a_TR[:,1:-1]
x_TF = a_TF[:,1:-1]
y = a_TR[:,-1]

In [12]:
x_TR

array([[0.66762425, 0.69008508, 0.03000983, 0.04606951, 0.73011178],
       [0.11714218, 0.56156555, 0.29293752, 0.90274863, 0.2218944 ],
       [0.89187216, 0.20013698, 0.25556631, 0.19665116, 0.24472207],
       [0.39631927, 0.92921709, 0.093175  , 0.91687989, 0.03886141],
       [0.94506655, 0.71930107, 0.25483908, 0.68514437, 0.38444584],
       [0.28372873, 0.64963147, 0.82207486, 0.22170495, 0.16464149],
       [0.3949477 , 0.96741946, 0.31785065, 0.37875874, 0.86229454],
       [0.35452093, 0.87840059, 0.37958744, 0.53836958, 0.69199712],
       [0.35041928, 0.97871691, 0.80263236, 0.28718004, 0.15236261],
       [0.59359602, 0.20444104, 0.86870111, 0.70567929, 0.26697481],
       [0.70821453, 0.58603904, 0.6939397 , 0.76059703, 0.61942613],
       [0.11341024, 0.28790636, 0.40589524, 0.85063979, 0.11519407],
       [0.96342645, 0.88960545, 0.09803749, 0.71043453, 0.19076562],
       [0.03787636, 0.6974486 , 0.83939417, 0.11890281, 0.63515982],
       [0.79574757, 0.73519385, 0.

In [13]:
x_TF

array([[0.39762187, 0.428217  , 0.85849594, 0.00718395, 0.60011128],
       [0.32981357, 0.13069243, 0.60692285, 0.71422182, 0.59879418],
       [0.13199014, 0.72875879, 0.40738409, 0.24158475, 0.38589026],
       [0.75439738, 0.79054342, 0.13337824, 0.54524955, 0.25917626],
       [0.57232671, 0.9638252 , 0.38947375, 0.25470109, 0.65362448],
       [0.97817223, 0.61106083, 0.62363625, 0.72867213, 0.06464778],
       [0.05268173, 0.46142051, 0.04118372, 0.62678967, 0.95070702],
       [0.74641146, 0.94531892, 0.75037293, 0.79414673, 0.05497092],
       [0.04550281, 0.77203602, 0.01373313, 0.19342784, 0.3368708 ],
       [0.84608988, 0.53909969, 0.46549684, 0.65834648, 0.87261171],
       [0.7005134 , 0.96111096, 0.15271778, 0.20656888, 0.89740983],
       [0.97112644, 0.75072302, 0.45352199, 0.60355105, 0.83889986],
       [0.98324205, 0.31223898, 0.67587886, 0.99575421, 0.42943838],
       [0.76143733, 0.92751293, 0.75313378, 0.48912292, 0.82519165],
       [0.22185936, 0.75450663, 0.

In [19]:
X = np.array([x_TR,x_TF]).transpose(1,0,2)

In [20]:
X.shape

(30, 2, 5)

In [22]:
y.shape

(30,)

In [23]:
import torch

In [28]:
X_T=torch.tensor(X).float()

In [29]:
X_T

tensor([[[0.6676, 0.6901, 0.0300, 0.0461, 0.7301],
         [0.3976, 0.4282, 0.8585, 0.0072, 0.6001]],

        [[0.1171, 0.5616, 0.2929, 0.9027, 0.2219],
         [0.3298, 0.1307, 0.6069, 0.7142, 0.5988]],

        [[0.8919, 0.2001, 0.2556, 0.1967, 0.2447],
         [0.1320, 0.7288, 0.4074, 0.2416, 0.3859]],

        [[0.3963, 0.9292, 0.0932, 0.9169, 0.0389],
         [0.7544, 0.7905, 0.1334, 0.5452, 0.2592]],

        [[0.9451, 0.7193, 0.2548, 0.6851, 0.3844],
         [0.5723, 0.9638, 0.3895, 0.2547, 0.6536]],

        [[0.2837, 0.6496, 0.8221, 0.2217, 0.1646],
         [0.9782, 0.6111, 0.6236, 0.7287, 0.0646]],

        [[0.3949, 0.9674, 0.3179, 0.3788, 0.8623],
         [0.0527, 0.4614, 0.0412, 0.6268, 0.9507]],

        [[0.3545, 0.8784, 0.3796, 0.5384, 0.6920],
         [0.7464, 0.9453, 0.7504, 0.7941, 0.0550]],

        [[0.3504, 0.9787, 0.8026, 0.2872, 0.1524],
         [0.0455, 0.7720, 0.0137, 0.1934, 0.3369]],

        [[0.5936, 0.2044, 0.8687, 0.7057, 0.2670],
         [0.8

In [30]:
X_T.shape, X_T.dtype

(torch.Size([30, 2, 5]), torch.float32)

In [31]:
X_T

tensor([[[0.6676, 0.6901, 0.0300, 0.0461, 0.7301],
         [0.3976, 0.4282, 0.8585, 0.0072, 0.6001]],

        [[0.1171, 0.5616, 0.2929, 0.9027, 0.2219],
         [0.3298, 0.1307, 0.6069, 0.7142, 0.5988]],

        [[0.8919, 0.2001, 0.2556, 0.1967, 0.2447],
         [0.1320, 0.7288, 0.4074, 0.2416, 0.3859]],

        [[0.3963, 0.9292, 0.0932, 0.9169, 0.0389],
         [0.7544, 0.7905, 0.1334, 0.5452, 0.2592]],

        [[0.9451, 0.7193, 0.2548, 0.6851, 0.3844],
         [0.5723, 0.9638, 0.3895, 0.2547, 0.6536]],

        [[0.2837, 0.6496, 0.8221, 0.2217, 0.1646],
         [0.9782, 0.6111, 0.6236, 0.7287, 0.0646]],

        [[0.3949, 0.9674, 0.3179, 0.3788, 0.8623],
         [0.0527, 0.4614, 0.0412, 0.6268, 0.9507]],

        [[0.3545, 0.8784, 0.3796, 0.5384, 0.6920],
         [0.7464, 0.9453, 0.7504, 0.7941, 0.0550]],

        [[0.3504, 0.9787, 0.8026, 0.2872, 0.1524],
         [0.0455, 0.7720, 0.0137, 0.1934, 0.3369]],

        [[0.5936, 0.2044, 0.8687, 0.7057, 0.2670],
         [0.8

In [32]:
ds=torch.utils.data.TensorDataset(X_T, torch.tensor(y).long())
ds

In [34]:
from torch.utils.data.dataset import random_split
train_val_ds, test_ds = random_split(ds, [0.8,0.2])

In [35]:
len(train_val_ds), len(test_ds)

(24, 6)

In [36]:
train_ds, val_ds = random_split(train_val_ds, [0.8,0.2])
len(train_ds), len(val_ds), len(test_ds)

(20, 4, 6)